# Site settings
title: today
subtitle: jacob since 2020.06
description: null
baseurl: null
url: "https://underain.github.io"

# Banner Section
hero: 112.jpg
hero-title: FOR SERVER

# Author - Creator
author-name: jacob kim
author-image: 10.jpg
about-author: My name is jacob kim.
author-email: tpghks9245@gmail.com

# Social Media Links (Links are located in hero and footer)
twitter: null
facebook: null
google-plus: null
instagram: null
pinterest: null
youtube: null

# Contact Form Settings
contact-subtitle: Pok pok listicle meggings, gluten-free deep v you probably haven't heard of them taxidermy iPhone gentrify seitan. Kogi cornhole enamel. # Title for the subscription form.

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: pretty
paginate: 9
paginate_path: "/page/:num"

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

plugins:
  - jekyll-paginate
  - jekyll-feed

include:
  - _pages

# Exclude from processing.
exclude:
 - Gemfile
 - Gemfile.lock
 - vendor
